__all__ = ["BaseModel",
           "UserModel",
           "ClassroomModel",
           "CourseModel",
           "DegreeModel",
           "ExamModel",
           "GroupModel",
           "ScheduleModel",
           "SubjectModel",
           "TeacherModel"]